# script:
# - docker run -e CI=true USERNAME/docker-react npm run test
language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nickmurr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nickmurr/docker-react npm run test
