# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app <id> #Linux

# docker run -p 3000:3000 -v /app/node_modules -v pwd:/app <id> #win
# docker run -p 3000:3000 -v /app/node_modules -v ${pwd}:/app <id> #win

FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm i

COPY . .

CMD ["npm", "start"]
